// Gen 1 Kanto: all 151 Pokemon (National Dex order), spriteId = PokeAPI sprite number
const POKEMON_LIST = [
  { id: 'bulbasaur', name: 'Bulbasaur', emoji: '•', spriteId: 1 },
  { id: 'ivysaur', name: 'Ivysaur', emoji: '•', spriteId: 2 },
  { id: 'venusaur', name: 'Venusaur', emoji: '•', spriteId: 3 },
  { id: 'charmander', name: 'Charmander', emoji: '•', spriteId: 4 },
  { id: 'charmeleon', name: 'Charmeleon', emoji: '•', spriteId: 5 },
  { id: 'charizard', name: 'Charizard', emoji: '•', spriteId: 6 },
  { id: 'squirtle', name: 'Squirtle', emoji: '•', spriteId: 7 },
  { id: 'wartortle', name: 'Wartortle', emoji: '•', spriteId: 8 },
  { id: 'blastoise', name: 'Blastoise', emoji: '•', spriteId: 9 },
  { id: 'caterpie', name: 'Caterpie', emoji: '•', spriteId: 10 },
  { id: 'metapod', name: 'Metapod', emoji: '•', spriteId: 11 },
  { id: 'butterfree', name: 'Butterfree', emoji: '•', spriteId: 12 },
  { id: 'weedle', name: 'Weedle', emoji: '•', spriteId: 13 },
  { id: 'kakuna', name: 'Kakuna', emoji: '•', spriteId: 14 },
  { id: 'beedrill', name: 'Beedrill', emoji: '•', spriteId: 15 },
  { id: 'pidgey', name: 'Pidgey', emoji: '•', spriteId: 16 },
  { id: 'pidgeotto', name: 'Pidgeotto', emoji: '•', spriteId: 17 },
  { id: 'pidgeot', name: 'Pidgeot', emoji: '•', spriteId: 18 },
  { id: 'rattata', name: 'Rattata', emoji: '•', spriteId: 19 },
  { id: 'raticate', name: 'Raticate', emoji: '•', spriteId: 20 },
  { id: 'spearow', name: 'Spearow', emoji: '•', spriteId: 21 },
  { id: 'fearow', name: 'Fearow', emoji: '•', spriteId: 22 },
  { id: 'ekans', name: 'Ekans', emoji: '•', spriteId: 23 },
  { id: 'arbok', name: 'Arbok', emoji: '•', spriteId: 24 },
  { id: 'pikachu', name: 'Pikachu', emoji: '•', spriteId: 25 },
  { id: 'raichu', name: 'Raichu', emoji: '•', spriteId: 26 },
  { id: 'sandshrew', name: 'Sandshrew', emoji: '•', spriteId: 27 },
  { id: 'sandslash', name: 'Sandslash', emoji: '•', spriteId: 28 },
  { id: 'nidoran-f', name: 'Nidoran♀', emoji: '•', spriteId: 29 },
  { id: 'nidorina', name: 'Nidorina', emoji: '•', spriteId: 30 },
  { id: 'nidoqueen', name: 'Nidoqueen', emoji: '•', spriteId: 31 },
  { id: 'nidoran-m', name: 'Nidoran♂', emoji: '•', spriteId: 32 },
  { id: 'nidorino', name: 'Nidorino', emoji: '•', spriteId: 33 },
  { id: 'nidoking', name: 'Nidoking', emoji: '•', spriteId: 34 },
  { id: 'clefairy', name: 'Clefairy', emoji: '•', spriteId: 35 },
  { id: 'clefable', name: 'Clefable', emoji: '•', spriteId: 36 },
  { id: 'vulpix', name: 'Vulpix', emoji: '•', spriteId: 37 },
  { id: 'ninetales', name: 'Ninetales', emoji: '•', spriteId: 38 },
  { id: 'jigglypuff', name: 'Jigglypuff', emoji: '•', spriteId: 39 },
  { id: 'wigglytuff', name: 'Wigglytuff', emoji: '•', spriteId: 40 },
  { id: 'zubat', name: 'Zubat', emoji: '•', spriteId: 41 },
  { id: 'golbat', name: 'Golbat', emoji: '•', spriteId: 42 },
  { id: 'oddish', name: 'Oddish', emoji: '•', spriteId: 43 },
  { id: 'gloom', name: 'Gloom', emoji: '•', spriteId: 44 },
  { id: 'vileplume', name: 'Vileplume', emoji: '•', spriteId: 45 },
  { id: 'paras', name: 'Paras', emoji: '•', spriteId: 46 },
  { id: 'parasect', name: 'Parasect', emoji: '•', spriteId: 47 },
  { id: 'venonat', name: 'Venonat', emoji: '•', spriteId: 48 },
  { id: 'venomoth', name: 'Venomoth', emoji: '•', spriteId: 49 },
  { id: 'diglett', name: 'Diglett', emoji: '•', spriteId: 50 },
  { id: 'dugtrio', name: 'Dugtrio', emoji: '•', spriteId: 51 },
  { id: 'meowth', name: 'Meowth', emoji: '•', spriteId: 52 },
  { id: 'persian', name: 'Persian', emoji: '•', spriteId: 53 },
  { id: 'psyduck', name: 'Psyduck', emoji: '•', spriteId: 54 },
  { id: 'golduck', name: 'Golduck', emoji: '•', spriteId: 55 },
  { id: 'mankey', name: 'Mankey', emoji: '•', spriteId: 56 },
  { id: 'primeape', name: 'Primeape', emoji: '•', spriteId: 57 },
  { id: 'growlithe', name: 'Growlithe', emoji: '•', spriteId: 58 },
  { id: 'arcanine', name: 'Arcanine', emoji: '•', spriteId: 59 },
  { id: 'poliwag', name: 'Poliwag', emoji: '•', spriteId: 60 },
  { id: 'poliwhirl', name: 'Poliwhirl', emoji: '•', spriteId: 61 },
  { id: 'poliwrath', name: 'Poliwrath', emoji: '•', spriteId: 62 },
  { id: 'abra', name: 'Abra', emoji: '•', spriteId: 63 },
  { id: 'kadabra', name: 'Kadabra', emoji: '•', spriteId: 64 },
  { id: 'alakazam', name: 'Alakazam', emoji: '•', spriteId: 65 },
  { id: 'machop', name: 'Machop', emoji: '•', spriteId: 66 },
  { id: 'machoke', name: 'Machoke', emoji: '•', spriteId: 67 },
  { id: 'machamp', name: 'Machamp', emoji: '•', spriteId: 68 },
  { id: 'bellsprout', name: 'Bellsprout', emoji: '•', spriteId: 69 },
  { id: 'weepinbell', name: 'Weepinbell', emoji: '•', spriteId: 70 },
  { id: 'victreebel', name: 'Victreebel', emoji: '•', spriteId: 71 },
  { id: 'tentacool', name: 'Tentacool', emoji: '•', spriteId: 72 },
  { id: 'tentacruel', name: 'Tentacruel', emoji: '•', spriteId: 73 },
  { id: 'geodude', name: 'Geodude', emoji: '•', spriteId: 74 },
  { id: 'graveler', name: 'Graveler', emoji: '•', spriteId: 75 },
  { id: 'golem', name: 'Golem', emoji: '•', spriteId: 76 },
  { id: 'ponyta', name: 'Ponyta', emoji: '•', spriteId: 77 },
  { id: 'rapidash', name: 'Rapidash', emoji: '•', spriteId: 78 },
  { id: 'slowpoke', name: 'Slowpoke', emoji: '•', spriteId: 79 },
  { id: 'slowbro', name: 'Slowbro', emoji: '•', spriteId: 80 },
  { id: 'magnemite', name: 'Magnemite', emoji: '•', spriteId: 81 },
  { id: 'magneton', name: 'Magneton', emoji: '•', spriteId: 82 },
  { id: 'farfetchd', name: "Farfetch'd", emoji: '•', spriteId: 83 },
  { id: 'doduo', name: 'Doduo', emoji: '•', spriteId: 84 },
  { id: 'dodrio', name: 'Dodrio', emoji: '•', spriteId: 85 },
  { id: 'seel', name: 'Seel', emoji: '•', spriteId: 86 },
  { id: 'dewgong', name: 'Dewgong', emoji: '•', spriteId: 87 },
  { id: 'grimer', name: 'Grimer', emoji: '•', spriteId: 88 },
  { id: 'muk', name: 'Muk', emoji: '•', spriteId: 89 },
  { id: 'shellder', name: 'Shellder', emoji: '•', spriteId: 90 },
  { id: 'cloyster', name: 'Cloyster', emoji: '•', spriteId: 91 },
  { id: 'gastly', name: 'Gastly', emoji: '•', spriteId: 92 },
  { id: 'haunter', name: 'Haunter', emoji: '•', spriteId: 93 },
  { id: 'gengar', name: 'Gengar', emoji: '•', spriteId: 94 },
  { id: 'onix', name: 'Onix', emoji: '•', spriteId: 95 },
  { id: 'drowzee', name: 'Drowzee', emoji: '•', spriteId: 96 },
  { id: 'hypno', name: 'Hypno', emoji: '•', spriteId: 97 },
  { id: 'krabby', name: 'Krabby', emoji: '•', spriteId: 98 },
  { id: 'kingler', name: 'Kingler', emoji: '•', spriteId: 99 },
  { id: 'voltorb', name: 'Voltorb', emoji: '•', spriteId: 100 },
  { id: 'electrode', name: 'Electrode', emoji: '•', spriteId: 101 },
  { id: 'exeggcute', name: 'Exeggcute', emoji: '•', spriteId: 102 },
  { id: 'exeggutor', name: 'Exeggutor', emoji: '•', spriteId: 103 },
  { id: 'cubone', name: 'Cubone', emoji: '•', spriteId: 104 },
  { id: 'marowak', name: 'Marowak', emoji: '•', spriteId: 105 },
  { id: 'hitmonlee', name: 'Hitmonlee', emoji: '•', spriteId: 106 },
  { id: 'hitmonchan', name: 'Hitmonchan', emoji: '•', spriteId: 107 },
  { id: 'lickitung', name: 'Lickitung', emoji: '•', spriteId: 108 },
  { id: 'koffing', name: 'Koffing', emoji: '•', spriteId: 109 },
  { id: 'weezing', name: 'Weezing', emoji: '•', spriteId: 110 },
  { id: 'rhyhorn', name: 'Rhyhorn', emoji: '•', spriteId: 111 },
  { id: 'rhydon', name: 'Rhydon', emoji: '•', spriteId: 112 },
  { id: 'chansey', name: 'Chansey', emoji: '•', spriteId: 113 },
  { id: 'tangela', name: 'Tangela', emoji: '•', spriteId: 114 },
  { id: 'kangaskhan', name: 'Kangaskhan', emoji: '•', spriteId: 115 },
  { id: 'horsea', name: 'Horsea', emoji: '•', spriteId: 116 },
  { id: 'seadra', name: 'Seadra', emoji: '•', spriteId: 117 },
  { id: 'goldeen', name: 'Goldeen', emoji: '•', spriteId: 118 },
  { id: 'seaking', name: 'Seaking', emoji: '•', spriteId: 119 },
  { id: 'staryu', name: 'Staryu', emoji: '•', spriteId: 120 },
  { id: 'starmie', name: 'Starmie', emoji: '•', spriteId: 121 },
  { id: 'mr-mime', name: 'Mr. Mime', emoji: '•', spriteId: 122 },
  { id: 'scyther', name: 'Scyther', emoji: '•', spriteId: 123 },
  { id: 'jynx', name: 'Jynx', emoji: '•', spriteId: 124 },
  { id: 'electabuzz', name: 'Electabuzz', emoji: '•', spriteId: 125 },
  { id: 'magmar', name: 'Magmar', emoji: '•', spriteId: 126 },
  { id: 'pinsir', name: 'Pinsir', emoji: '•', spriteId: 127 },
  { id: 'tauros', name: 'Tauros', emoji: '•', spriteId: 128 },
  { id: 'magikarp', name: 'Magikarp', emoji: '•', spriteId: 129 },
  { id: 'gyarados', name: 'Gyarados', emoji: '•', spriteId: 130 },
  { id: 'lapras', name: 'Lapras', emoji: '•', spriteId: 131 },
  { id: 'ditto', name: 'Ditto', emoji: '•', spriteId: 132 },
  { id: 'eevee', name: 'Eevee', emoji: '•', spriteId: 133 },
  { id: 'vaporeon', name: 'Vaporeon', emoji: '•', spriteId: 134 },
  { id: 'jolteon', name: 'Jolteon', emoji: '•', spriteId: 135 },
  { id: 'flareon', name: 'Flareon', emoji: '•', spriteId: 136 },
  { id: 'porygon', name: 'Porygon', emoji: '•', spriteId: 137 },
  { id: 'omanyte', name: 'Omanyte', emoji: '•', spriteId: 138 },
  { id: 'omastar', name: 'Omastar', emoji: '•', spriteId: 139 },
  { id: 'kabuto', name: 'Kabuto', emoji: '•', spriteId: 140 },
  { id: 'kabutops', name: 'Kabutops', emoji: '•', spriteId: 141 },
  { id: 'aerodactyl', name: 'Aerodactyl', emoji: '•', spriteId: 142 },
  { id: 'snorlax', name: 'Snorlax', emoji: '•', spriteId: 143 },
  { id: 'articuno', name: 'Articuno', emoji: '•', spriteId: 144 },
  { id: 'zapdos', name: 'Zapdos', emoji: '•', spriteId: 145 },
  { id: 'moltres', name: 'Moltres', emoji: '•', spriteId: 146 },
  { id: 'dratini', name: 'Dratini', emoji: '•', spriteId: 147 },
  { id: 'dragonair', name: 'Dragonair', emoji: '•', spriteId: 148 },
  { id: 'dragonite', name: 'Dragonite', emoji: '•', spriteId: 149 },
  { id: 'mewtwo', name: 'Mewtwo', emoji: '•', spriteId: 150 },
  { id: 'mew', name: 'Mew', emoji: '•', spriteId: 151 }
]

// Evolution stage: 0 = base (3 questions), 1 = 1st evolution (4), 2 = 2nd evolution (5)
const EVOLUTION_STAGE = {
  bulbasaur: 0, ivysaur: 1, venusaur: 2, charmander: 0, charmeleon: 1, charizard: 2,
  squirtle: 0, wartortle: 1, blastoise: 2, caterpie: 0, metapod: 1, butterfree: 2,
  weedle: 0, kakuna: 1, beedrill: 2, pidgey: 0, pidgeotto: 1, pidgeot: 2,
  rattata: 0, raticate: 1, spearow: 0, fearow: 1, ekans: 0, arbok: 1,
  pikachu: 0, raichu: 1, sandshrew: 0, sandslash: 1, 'nidoran-f': 0, nidorina: 1, nidoqueen: 2,
  'nidoran-m': 0, nidorino: 1, nidoking: 2, clefairy: 0, clefable: 1, vulpix: 0, ninetales: 1,
  jigglypuff: 0, wigglytuff: 1, zubat: 0, golbat: 1, oddish: 0, gloom: 1, vileplume: 2,
  paras: 0, parasect: 1, venonat: 0, venomoth: 1, diglett: 0, dugtrio: 1,
  meowth: 0, persian: 1, psyduck: 0, golduck: 1, mankey: 0, primeape: 1,
  growlithe: 0, arcanine: 1, poliwag: 0, poliwhirl: 1, poliwrath: 2,
  abra: 0, kadabra: 1, alakazam: 2, machop: 0, machoke: 1, machamp: 2,
  bellsprout: 0, weepinbell: 1, victreebel: 2, tentacool: 0, tentacruel: 1,
  geodude: 0, graveler: 1, golem: 2, ponyta: 0, rapidash: 1, slowpoke: 0, slowbro: 1,
  magnemite: 0, magneton: 1, farfetchd: 0, doduo: 0, dodrio: 1, seel: 0, dewgong: 1,
  grimer: 0, muk: 1, shellder: 0, cloyster: 1, gastly: 0, haunter: 1, gengar: 2,
  onix: 0, drowzee: 0, hypno: 1, krabby: 0, kingler: 1, voltorb: 0, electrode: 1,
  exeggcute: 0, exeggutor: 1, cubone: 0, marowak: 1, hitmonlee: 0, hitmonchan: 0,
  lickitung: 0, koffing: 0, weezing: 1, rhyhorn: 0, rhydon: 1, chansey: 0, tangela: 0,
  kangaskhan: 0, horsea: 0, seadra: 1, goldeen: 0, seaking: 1, staryu: 0, starmie: 1,
  'mr-mime': 0, scyther: 0, jynx: 0, electabuzz: 0, magmar: 0, pinsir: 0, tauros: 0,
  magikarp: 0, gyarados: 1, lapras: 0, ditto: 0, eevee: 0, vaporeon: 1, jolteon: 1, flareon: 1,
  porygon: 0, omanyte: 0, omastar: 1, kabuto: 0, kabutops: 1, aerodactyl: 0, snorlax: 0,
  articuno: 0, zapdos: 0, moltres: 0, dratini: 0, dragonair: 1, dragonite: 2, mewtwo: 0, mew: 0
}

// Next evolution: id -> next form id, or null if fully evolved / no evolution
const NEXT_EVOLUTION = {
  bulbasaur: 'ivysaur', ivysaur: 'venusaur', venusaur: null, charmander: 'charmeleon', charmeleon: 'charizard', charizard: null,
  squirtle: 'wartortle', wartortle: 'blastoise', blastoise: null, caterpie: 'metapod', metapod: 'butterfree', butterfree: null,
  weedle: 'kakuna', kakuna: 'beedrill', beedrill: null, pidgey: 'pidgeotto', pidgeotto: 'pidgeot', pidgeot: null,
  rattata: 'raticate', raticate: null, spearow: 'fearow', fearow: null, ekans: 'arbok', arbok: null,
  pikachu: 'raichu', raichu: null, sandshrew: 'sandslash', sandslash: null, 'nidoran-f': 'nidorina', nidorina: 'nidoqueen', nidoqueen: null,
  'nidoran-m': 'nidorino', nidorino: 'nidoking', nidoking: null, clefairy: 'clefable', clefable: null, vulpix: 'ninetales', ninetales: null,
  jigglypuff: 'wigglytuff', wigglytuff: null, zubat: 'golbat', golbat: null, oddish: 'gloom', gloom: 'vileplume', vileplume: null,
  paras: 'parasect', parasect: null, venonat: 'venomoth', venomoth: null, diglett: 'dugtrio', dugtrio: null,
  meowth: 'persian', persian: null, psyduck: 'golduck', golduck: null, mankey: 'primeape', primeape: null,
  growlithe: 'arcanine', arcanine: null, poliwag: 'poliwhirl', poliwhirl: 'poliwrath', poliwrath: null,
  abra: 'kadabra', kadabra: 'alakazam', alakazam: null, machop: 'machoke', machoke: 'machamp', machamp: null,
  bellsprout: 'weepinbell', weepinbell: 'victreebel', victreebel: null, tentacool: 'tentacruel', tentacruel: null,
  geodude: 'graveler', graveler: 'golem', golem: null, ponyta: 'rapidash', rapidash: null, slowpoke: 'slowbro', slowbro: null,
  magnemite: 'magneton', magneton: null, farfetchd: null, doduo: 'dodrio', dodrio: null, seel: 'dewgong', dewgong: null,
  grimer: 'muk', muk: null, shellder: 'cloyster', cloyster: null, gastly: 'haunter', haunter: 'gengar', gengar: null,
  onix: null, drowzee: 'hypno', hypno: null, krabby: 'kingler', kingler: null, voltorb: 'electrode', electrode: null,
  exeggcute: 'exeggutor', exeggutor: null, cubone: 'marowak', marowak: null, hitmonlee: null, hitmonchan: null,
  lickitung: null, koffing: 'weezing', weezing: null, rhyhorn: 'rhydon', rhydon: null, chansey: null, tangela: null,
  kangaskhan: null, horsea: 'seadra', seadra: null, goldeen: 'seaking', seaking: null, staryu: 'starmie', starmie: null,
  'mr-mime': null, scyther: null, jynx: null, electabuzz: null, magmar: null, pinsir: null, tauros: null,
  magikarp: 'gyarados', gyarados: null, lapras: null, ditto: null, eevee: null, vaporeon: null, jolteon: null, flareon: null,
  porygon: null, omanyte: 'omastar', omastar: null, kabuto: 'kabutops', kabutops: null, aerodactyl: null, snorlax: null,
  articuno: null, zapdos: null, moltres: null, dratini: 'dragonair', dragonair: 'dragonite', dragonite: null, mewtwo: null, mew: null
}

// Pokémon with multiple possible evolutions (e.g. Eevee) – id -> array of next form ids
const MULTI_EVOLUTIONS = {
  eevee: ['vaporeon', 'jolteon', 'flareon']
}

// Base form of each evolution line (first form in chain)
const BASE_FORM = {
  bulbasaur: 'bulbasaur', ivysaur: 'bulbasaur', venusaur: 'bulbasaur', charmander: 'charmander', charmeleon: 'charmander', charizard: 'charmander',
  squirtle: 'squirtle', wartortle: 'squirtle', blastoise: 'squirtle', caterpie: 'caterpie', metapod: 'caterpie', butterfree: 'caterpie',
  weedle: 'weedle', kakuna: 'weedle', beedrill: 'weedle', pidgey: 'pidgey', pidgeotto: 'pidgey', pidgeot: 'pidgey',
  rattata: 'rattata', raticate: 'rattata', spearow: 'spearow', fearow: 'spearow', ekans: 'ekans', arbok: 'ekans',
  pikachu: 'pikachu', raichu: 'pikachu', sandshrew: 'sandshrew', sandslash: 'sandshrew', 'nidoran-f': 'nidoran-f', nidorina: 'nidoran-f', nidoqueen: 'nidoran-f',
  'nidoran-m': 'nidoran-m', nidorino: 'nidoran-m', nidoking: 'nidoran-m', clefairy: 'clefairy', clefable: 'clefairy', vulpix: 'vulpix', ninetales: 'vulpix',
  jigglypuff: 'jigglypuff', wigglytuff: 'jigglypuff', zubat: 'zubat', golbat: 'zubat', oddish: 'oddish', gloom: 'oddish', vileplume: 'oddish',
  paras: 'paras', parasect: 'paras', venonat: 'venonat', venomoth: 'venonat', diglett: 'diglett', dugtrio: 'diglett',
  meowth: 'meowth', persian: 'meowth', psyduck: 'psyduck', golduck: 'psyduck', mankey: 'mankey', primeape: 'mankey',
  growlithe: 'growlithe', arcanine: 'growlithe', poliwag: 'poliwag', poliwhirl: 'poliwag', poliwrath: 'poliwag',
  abra: 'abra', kadabra: 'abra', alakazam: 'abra', machop: 'machop', machoke: 'machop', machamp: 'machop',
  bellsprout: 'bellsprout', weepinbell: 'bellsprout', victreebel: 'bellsprout', tentacool: 'tentacool', tentacruel: 'tentacool',
  geodude: 'geodude', graveler: 'geodude', golem: 'geodude', ponyta: 'ponyta', rapidash: 'ponyta', slowpoke: 'slowpoke', slowbro: 'slowpoke',
  magnemite: 'magnemite', magneton: 'magnemite', farfetchd: 'farfetchd', doduo: 'doduo', dodrio: 'doduo', seel: 'seel', dewgong: 'seel',
  grimer: 'grimer', muk: 'grimer', shellder: 'shellder', cloyster: 'shellder', gastly: 'gastly', haunter: 'gastly', gengar: 'gastly',
  onix: 'onix', drowzee: 'drowzee', hypno: 'drowzee', krabby: 'krabby', kingler: 'krabby', voltorb: 'voltorb', electrode: 'voltorb',
  exeggcute: 'exeggcute', exeggutor: 'exeggcute', cubone: 'cubone', marowak: 'cubone', hitmonlee: 'hitmonlee', hitmonchan: 'hitmonchan',
  lickitung: 'lickitung', koffing: 'koffing', weezing: 'koffing', rhyhorn: 'rhyhorn', rhydon: 'rhyhorn', chansey: 'chansey', tangela: 'tangela',
  kangaskhan: 'kangaskhan', horsea: 'horsea', seadra: 'horsea', goldeen: 'goldeen', seaking: 'goldeen', staryu: 'staryu', starmie: 'staryu',
  'mr-mime': 'mr-mime', scyther: 'scyther', jynx: 'jynx', electabuzz: 'electabuzz', magmar: 'magmar', pinsir: 'pinsir', tauros: 'tauros',
  magikarp: 'magikarp', gyarados: 'magikarp', lapras: 'lapras', ditto: 'ditto', eevee: 'eevee', vaporeon: 'eevee', jolteon: 'eevee', flareon: 'eevee',
  porygon: 'porygon', omanyte: 'omanyte', omastar: 'omanyte', kabuto: 'kabuto', kabutops: 'kabuto', aerodactyl: 'aerodactyl', snorlax: 'snorlax',
  articuno: 'articuno', zapdos: 'zapdos', moltres: 'moltres', dratini: 'dratini', dragonair: 'dratini', dragonite: 'dratini', mewtwo: 'mewtwo', mew: 'mew'
}

// Starters: always selectable. Extra caught Pokémon are loaded from data/caught.json
const STARTER_IDS = ['bulbasaur', 'charmander', 'squirtle', 'pikachu', 'eevee']
