// Gen 1–2: National Dex order (#1–251), spriteId = PokeAPI national dex sprite number
const POKEMON_LIST = [
  { id: 'bulbasaur', name: 'Bulbasaur', emoji: '•', spriteId: 1 },
  { id: 'ivysaur', name: 'Ivysaur', emoji: '•', spriteId: 2 },
  { id: 'venusaur', name: 'Venusaur', emoji: '•', spriteId: 3 },
  { id: 'charmander', name: 'Charmander', emoji: '•', spriteId: 4 },
  { id: 'charmeleon', name: 'Charmeleon', emoji: '•', spriteId: 5 },
  { id: 'charizard', name: 'Charizard', emoji: '•', spriteId: 6 },
  { id: 'squirtle', name: 'Squirtle', emoji: '•', spriteId: 7 },
  { id: 'wartortle', name: 'Wartortle', emoji: '•', spriteId: 8 },
  { id: 'blastoise', name: 'Blastoise', emoji: '•', spriteId: 9 },
  { id: 'caterpie', name: 'Caterpie', emoji: '•', spriteId: 10 },
  { id: 'metapod', name: 'Metapod', emoji: '•', spriteId: 11 },
  { id: 'butterfree', name: 'Butterfree', emoji: '•', spriteId: 12 },
  { id: 'weedle', name: 'Weedle', emoji: '•', spriteId: 13 },
  { id: 'kakuna', name: 'Kakuna', emoji: '•', spriteId: 14 },
  { id: 'beedrill', name: 'Beedrill', emoji: '•', spriteId: 15 },
  { id: 'pidgey', name: 'Pidgey', emoji: '•', spriteId: 16 },
  { id: 'pidgeotto', name: 'Pidgeotto', emoji: '•', spriteId: 17 },
  { id: 'pidgeot', name: 'Pidgeot', emoji: '•', spriteId: 18 },
  { id: 'rattata', name: 'Rattata', emoji: '•', spriteId: 19 },
  { id: 'raticate', name: 'Raticate', emoji: '•', spriteId: 20 },
  { id: 'spearow', name: 'Spearow', emoji: '•', spriteId: 21 },
  { id: 'fearow', name: 'Fearow', emoji: '•', spriteId: 22 },
  { id: 'ekans', name: 'Ekans', emoji: '•', spriteId: 23 },
  { id: 'arbok', name: 'Arbok', emoji: '•', spriteId: 24 },
  { id: 'pikachu', name: 'Pikachu', emoji: '•', spriteId: 25 },
  { id: 'raichu', name: 'Raichu', emoji: '•', spriteId: 26 },
  { id: 'sandshrew', name: 'Sandshrew', emoji: '•', spriteId: 27 },
  { id: 'sandslash', name: 'Sandslash', emoji: '•', spriteId: 28 },
  { id: 'nidoran-f', name: 'Nidoran♀', emoji: '•', spriteId: 29 },
  { id: 'nidorina', name: 'Nidorina', emoji: '•', spriteId: 30 },
  { id: 'nidoqueen', name: 'Nidoqueen', emoji: '•', spriteId: 31 },
  { id: 'nidoran-m', name: 'Nidoran♂', emoji: '•', spriteId: 32 },
  { id: 'nidorino', name: 'Nidorino', emoji: '•', spriteId: 33 },
  { id: 'nidoking', name: 'Nidoking', emoji: '•', spriteId: 34 },
  { id: 'clefairy', name: 'Clefairy', emoji: '•', spriteId: 35 },
  { id: 'clefable', name: 'Clefable', emoji: '•', spriteId: 36 },
  { id: 'vulpix', name: 'Vulpix', emoji: '•', spriteId: 37 },
  { id: 'ninetales', name: 'Ninetales', emoji: '•', spriteId: 38 },
  { id: 'jigglypuff', name: 'Jigglypuff', emoji: '•', spriteId: 39 },
  { id: 'wigglytuff', name: 'Wigglytuff', emoji: '•', spriteId: 40 },
  { id: 'zubat', name: 'Zubat', emoji: '•', spriteId: 41 },
  { id: 'golbat', name: 'Golbat', emoji: '•', spriteId: 42 },
  { id: 'oddish', name: 'Oddish', emoji: '•', spriteId: 43 },
  { id: 'gloom', name: 'Gloom', emoji: '•', spriteId: 44 },
  { id: 'vileplume', name: 'Vileplume', emoji: '•', spriteId: 45 },
  { id: 'paras', name: 'Paras', emoji: '•', spriteId: 46 },
  { id: 'parasect', name: 'Parasect', emoji: '•', spriteId: 47 },
  { id: 'venonat', name: 'Venonat', emoji: '•', spriteId: 48 },
  { id: 'venomoth', name: 'Venomoth', emoji: '•', spriteId: 49 },
  { id: 'diglett', name: 'Diglett', emoji: '•', spriteId: 50 },
  { id: 'dugtrio', name: 'Dugtrio', emoji: '•', spriteId: 51 },
  { id: 'meowth', name: 'Meowth', emoji: '•', spriteId: 52 },
  { id: 'persian', name: 'Persian', emoji: '•', spriteId: 53 },
  { id: 'psyduck', name: 'Psyduck', emoji: '•', spriteId: 54 },
  { id: 'golduck', name: 'Golduck', emoji: '•', spriteId: 55 },
  { id: 'mankey', name: 'Mankey', emoji: '•', spriteId: 56 },
  { id: 'primeape', name: 'Primeape', emoji: '•', spriteId: 57 },
  { id: 'growlithe', name: 'Growlithe', emoji: '•', spriteId: 58 },
  { id: 'arcanine', name: 'Arcanine', emoji: '•', spriteId: 59 },
  { id: 'poliwag', name: 'Poliwag', emoji: '•', spriteId: 60 },
  { id: 'poliwhirl', name: 'Poliwhirl', emoji: '•', spriteId: 61 },
  { id: 'poliwrath', name: 'Poliwrath', emoji: '•', spriteId: 62 },
  { id: 'abra', name: 'Abra', emoji: '•', spriteId: 63 },
  { id: 'kadabra', name: 'Kadabra', emoji: '•', spriteId: 64 },
  { id: 'alakazam', name: 'Alakazam', emoji: '•', spriteId: 65 },
  { id: 'machop', name: 'Machop', emoji: '•', spriteId: 66 },
  { id: 'machoke', name: 'Machoke', emoji: '•', spriteId: 67 },
  { id: 'machamp', name: 'Machamp', emoji: '•', spriteId: 68 },
  { id: 'bellsprout', name: 'Bellsprout', emoji: '•', spriteId: 69 },
  { id: 'weepinbell', name: 'Weepinbell', emoji: '•', spriteId: 70 },
  { id: 'victreebel', name: 'Victreebel', emoji: '•', spriteId: 71 },
  { id: 'tentacool', name: 'Tentacool', emoji: '•', spriteId: 72 },
  { id: 'tentacruel', name: 'Tentacruel', emoji: '•', spriteId: 73 },
  { id: 'geodude', name: 'Geodude', emoji: '•', spriteId: 74 },
  { id: 'graveler', name: 'Graveler', emoji: '•', spriteId: 75 },
  { id: 'golem', name: 'Golem', emoji: '•', spriteId: 76 },
  { id: 'ponyta', name: 'Ponyta', emoji: '•', spriteId: 77 },
  { id: 'rapidash', name: 'Rapidash', emoji: '•', spriteId: 78 },
  { id: 'slowpoke', name: 'Slowpoke', emoji: '•', spriteId: 79 },
  { id: 'slowbro', name: 'Slowbro', emoji: '•', spriteId: 80 },
  { id: 'magnemite', name: 'Magnemite', emoji: '•', spriteId: 81 },
  { id: 'magneton', name: 'Magneton', emoji: '•', spriteId: 82 },
  { id: 'farfetchd', name: "Farfetch'd", emoji: '•', spriteId: 83 },
  { id: 'doduo', name: 'Doduo', emoji: '•', spriteId: 84 },
  { id: 'dodrio', name: 'Dodrio', emoji: '•', spriteId: 85 },
  { id: 'seel', name: 'Seel', emoji: '•', spriteId: 86 },
  { id: 'dewgong', name: 'Dewgong', emoji: '•', spriteId: 87 },
  { id: 'grimer', name: 'Grimer', emoji: '•', spriteId: 88 },
  { id: 'muk', name: 'Muk', emoji: '•', spriteId: 89 },
  { id: 'shellder', name: 'Shellder', emoji: '•', spriteId: 90 },
  { id: 'cloyster', name: 'Cloyster', emoji: '•', spriteId: 91 },
  { id: 'gastly', name: 'Gastly', emoji: '•', spriteId: 92 },
  { id: 'haunter', name: 'Haunter', emoji: '•', spriteId: 93 },
  { id: 'gengar', name: 'Gengar', emoji: '•', spriteId: 94 },
  { id: 'onix', name: 'Onix', emoji: '•', spriteId: 95 },
  { id: 'drowzee', name: 'Drowzee', emoji: '•', spriteId: 96 },
  { id: 'hypno', name: 'Hypno', emoji: '•', spriteId: 97 },
  { id: 'krabby', name: 'Krabby', emoji: '•', spriteId: 98 },
  { id: 'kingler', name: 'Kingler', emoji: '•', spriteId: 99 },
  { id: 'voltorb', name: 'Voltorb', emoji: '•', spriteId: 100 },
  { id: 'electrode', name: 'Electrode', emoji: '•', spriteId: 101 },
  { id: 'exeggcute', name: 'Exeggcute', emoji: '•', spriteId: 102 },
  { id: 'exeggutor', name: 'Exeggutor', emoji: '•', spriteId: 103 },
  { id: 'cubone', name: 'Cubone', emoji: '•', spriteId: 104 },
  { id: 'marowak', name: 'Marowak', emoji: '•', spriteId: 105 },
  { id: 'hitmonlee', name: 'Hitmonlee', emoji: '•', spriteId: 106 },
  { id: 'hitmonchan', name: 'Hitmonchan', emoji: '•', spriteId: 107 },
  { id: 'lickitung', name: 'Lickitung', emoji: '•', spriteId: 108 },
  { id: 'koffing', name: 'Koffing', emoji: '•', spriteId: 109 },
  { id: 'weezing', name: 'Weezing', emoji: '•', spriteId: 110 },
  { id: 'rhyhorn', name: 'Rhyhorn', emoji: '•', spriteId: 111 },
  { id: 'rhydon', name: 'Rhydon', emoji: '•', spriteId: 112 },
  { id: 'chansey', name: 'Chansey', emoji: '•', spriteId: 113 },
  { id: 'tangela', name: 'Tangela', emoji: '•', spriteId: 114 },
  { id: 'kangaskhan', name: 'Kangaskhan', emoji: '•', spriteId: 115 },
  { id: 'horsea', name: 'Horsea', emoji: '•', spriteId: 116 },
  { id: 'seadra', name: 'Seadra', emoji: '•', spriteId: 117 },
  { id: 'goldeen', name: 'Goldeen', emoji: '•', spriteId: 118 },
  { id: 'seaking', name: 'Seaking', emoji: '•', spriteId: 119 },
  { id: 'staryu', name: 'Staryu', emoji: '•', spriteId: 120 },
  { id: 'starmie', name: 'Starmie', emoji: '•', spriteId: 121 },
  { id: 'mr-mime', name: 'Mr. Mime', emoji: '•', spriteId: 122 },
  { id: 'scyther', name: 'Scyther', emoji: '•', spriteId: 123 },
  { id: 'jynx', name: 'Jynx', emoji: '•', spriteId: 124 },
  { id: 'electabuzz', name: 'Electabuzz', emoji: '•', spriteId: 125 },
  { id: 'magmar', name: 'Magmar', emoji: '•', spriteId: 126 },
  { id: 'pinsir', name: 'Pinsir', emoji: '•', spriteId: 127 },
  { id: 'tauros', name: 'Tauros', emoji: '•', spriteId: 128 },
  { id: 'magikarp', name: 'Magikarp', emoji: '•', spriteId: 129 },
  { id: 'gyarados', name: 'Gyarados', emoji: '•', spriteId: 130 },
  { id: 'lapras', name: 'Lapras', emoji: '•', spriteId: 131 },
  { id: 'ditto', name: 'Ditto', emoji: '•', spriteId: 132 },
  { id: 'eevee', name: 'Eevee', emoji: '•', spriteId: 133 },
  { id: 'vaporeon', name: 'Vaporeon', emoji: '•', spriteId: 134 },
  { id: 'jolteon', name: 'Jolteon', emoji: '•', spriteId: 135 },
  { id: 'flareon', name: 'Flareon', emoji: '•', spriteId: 136 },
  { id: 'porygon', name: 'Porygon', emoji: '•', spriteId: 137 },
  { id: 'omanyte', name: 'Omanyte', emoji: '•', spriteId: 138 },
  { id: 'omastar', name: 'Omastar', emoji: '•', spriteId: 139 },
  { id: 'kabuto', name: 'Kabuto', emoji: '•', spriteId: 140 },
  { id: 'kabutops', name: 'Kabutops', emoji: '•', spriteId: 141 },
  { id: 'aerodactyl', name: 'Aerodactyl', emoji: '•', spriteId: 142 },
  { id: 'snorlax', name: 'Snorlax', emoji: '•', spriteId: 143 },
  { id: 'articuno', name: 'Articuno', emoji: '•', spriteId: 144 },
  { id: 'zapdos', name: 'Zapdos', emoji: '•', spriteId: 145 },
  { id: 'moltres', name: 'Moltres', emoji: '•', spriteId: 146 },
  { id: 'dratini', name: 'Dratini', emoji: '•', spriteId: 147 },
  { id: 'dragonair', name: 'Dragonair', emoji: '•', spriteId: 148 },
  { id: 'dragonite', name: 'Dragonite', emoji: '•', spriteId: 149 },
  { id: 'mewtwo', name: 'Mewtwo', emoji: '•', spriteId: 150 },
  { id: 'mew', name: 'Mew', emoji: '•', spriteId: 151 },
  { id: 'chikorita', name: 'Chikorita', emoji: '•', spriteId: 152 },
  { id: 'bayleef', name: 'Bayleef', emoji: '•', spriteId: 153 },
  { id: 'meganium', name: 'Meganium', emoji: '•', spriteId: 154 },
  { id: 'cyndaquil', name: 'Cyndaquil', emoji: '•', spriteId: 155 },
  { id: 'quilava', name: 'Quilava', emoji: '•', spriteId: 156 },
  { id: 'typhlosion', name: 'Typhlosion', emoji: '•', spriteId: 157 },
  { id: 'totodile', name: 'Totodile', emoji: '•', spriteId: 158 },
  { id: 'croconaw', name: 'Croconaw', emoji: '•', spriteId: 159 },
  { id: 'feraligatr', name: 'Feraligatr', emoji: '•', spriteId: 160 },
  { id: 'sentret', name: 'Sentret', emoji: '•', spriteId: 161 },
  { id: 'furret', name: 'Furret', emoji: '•', spriteId: 162 },
  { id: 'hoothoot', name: 'Hoothoot', emoji: '•', spriteId: 163 },
  { id: 'noctowl', name: 'Noctowl', emoji: '•', spriteId: 164 },
  { id: 'ledyba', name: 'Ledyba', emoji: '•', spriteId: 165 },
  { id: 'ledian', name: 'Ledian', emoji: '•', spriteId: 166 },
  { id: 'spinarak', name: 'Spinarak', emoji: '•', spriteId: 167 },
  { id: 'ariados', name: 'Ariados', emoji: '•', spriteId: 168 },
  { id: 'crobat', name: 'Crobat', emoji: '•', spriteId: 169 },
  { id: 'chinchou', name: 'Chinchou', emoji: '•', spriteId: 170 },
  { id: 'lanturn', name: 'Lanturn', emoji: '•', spriteId: 171 },
  { id: 'pichu', name: 'Pichu', emoji: '•', spriteId: 172 },
  { id: 'cleffa', name: 'Cleffa', emoji: '•', spriteId: 173 },
  { id: 'igglybuff', name: 'Igglybuff', emoji: '•', spriteId: 174 },
  { id: 'togepi', name: 'Togepi', emoji: '•', spriteId: 175 },
  { id: 'togetic', name: 'Togetic', emoji: '•', spriteId: 176 },
  { id: 'natu', name: 'Natu', emoji: '•', spriteId: 177 },
  { id: 'xatu', name: 'Xatu', emoji: '•', spriteId: 178 },
  { id: 'mareep', name: 'Mareep', emoji: '•', spriteId: 179 },
  { id: 'flaaffy', name: 'Flaaffy', emoji: '•', spriteId: 180 },
  { id: 'ampharos', name: 'Ampharos', emoji: '•', spriteId: 181 },
  { id: 'bellossom', name: 'Bellossom', emoji: '•', spriteId: 182 },
  { id: 'marill', name: 'Marill', emoji: '•', spriteId: 183 },
  { id: 'azumarill', name: 'Azumarill', emoji: '•', spriteId: 184 },
  { id: 'sudowoodo', name: 'Sudowoodo', emoji: '•', spriteId: 185 },
  { id: 'politoed', name: 'Politoed', emoji: '•', spriteId: 186 },
  { id: 'hoppip', name: 'Hoppip', emoji: '•', spriteId: 187 },
  { id: 'skiploom', name: 'Skiploom', emoji: '•', spriteId: 188 },
  { id: 'jumpluff', name: 'Jumpluff', emoji: '•', spriteId: 189 },
  { id: 'aipom', name: 'Aipom', emoji: '•', spriteId: 190 },
  { id: 'sunkern', name: 'Sunkern', emoji: '•', spriteId: 191 },
  { id: 'sunflora', name: 'Sunflora', emoji: '•', spriteId: 192 },
  { id: 'yanma', name: 'Yanma', emoji: '•', spriteId: 193 },
  { id: 'wooper', name: 'Wooper', emoji: '•', spriteId: 194 },
  { id: 'quagsire', name: 'Quagsire', emoji: '•', spriteId: 195 },
  { id: 'espeon', name: 'Espeon', emoji: '•', spriteId: 196 },
  { id: 'umbreon', name: 'Umbreon', emoji: '•', spriteId: 197 },
  { id: 'murkrow', name: 'Murkrow', emoji: '•', spriteId: 198 },
  { id: 'slowking', name: 'Slowking', emoji: '•', spriteId: 199 },
  { id: 'misdreavus', name: 'Misdreavus', emoji: '•', spriteId: 200 },
  { id: 'unown', name: 'Unown', emoji: '•', spriteId: 201 },
  { id: 'wobbuffet', name: 'Wobbuffet', emoji: '•', spriteId: 202 },
  { id: 'girafarig', name: 'Girafarig', emoji: '•', spriteId: 203 },
  { id: 'pineco', name: 'Pineco', emoji: '•', spriteId: 204 },
  { id: 'forretress', name: 'Forretress', emoji: '•', spriteId: 205 },
  { id: 'dunsparce', name: 'Dunsparce', emoji: '•', spriteId: 206 },
  { id: 'gligar', name: 'Gligar', emoji: '•', spriteId: 207 },
  { id: 'steelix', name: 'Steelix', emoji: '•', spriteId: 208 },
  { id: 'snubbull', name: 'Snubbull', emoji: '•', spriteId: 209 },
  { id: 'granbull', name: 'Granbull', emoji: '•', spriteId: 210 },
  { id: 'qwilfish', name: 'Qwilfish', emoji: '•', spriteId: 211 },
  { id: 'scizor', name: 'Scizor', emoji: '•', spriteId: 212 },
  { id: 'shuckle', name: 'Shuckle', emoji: '•', spriteId: 213 },
  { id: 'heracross', name: 'Heracross', emoji: '•', spriteId: 214 },
  { id: 'sneasel', name: 'Sneasel', emoji: '•', spriteId: 215 },
  { id: 'teddiursa', name: 'Teddiursa', emoji: '•', spriteId: 216 },
  { id: 'ursaring', name: 'Ursaring', emoji: '•', spriteId: 217 },
  { id: 'slugma', name: 'Slugma', emoji: '•', spriteId: 218 },
  { id: 'magcargo', name: 'Magcargo', emoji: '•', spriteId: 219 },
  { id: 'swinub', name: 'Swinub', emoji: '•', spriteId: 220 },
  { id: 'piloswine', name: 'Piloswine', emoji: '•', spriteId: 221 },
  { id: 'corsola', name: 'Corsola', emoji: '•', spriteId: 222 },
  { id: 'remoraid', name: 'Remoraid', emoji: '•', spriteId: 223 },
  { id: 'octillery', name: 'Octillery', emoji: '•', spriteId: 224 },
  { id: 'delibird', name: 'Delibird', emoji: '•', spriteId: 225 },
  { id: 'mantine', name: 'Mantine', emoji: '•', spriteId: 226 },
  { id: 'skarmory', name: 'Skarmory', emoji: '•', spriteId: 227 },
  { id: 'houndour', name: 'Houndour', emoji: '•', spriteId: 228 },
  { id: 'houndoom', name: 'Houndoom', emoji: '•', spriteId: 229 },
  { id: 'kingdra', name: 'Kingdra', emoji: '•', spriteId: 230 },
  { id: 'phanpy', name: 'Phanpy', emoji: '•', spriteId: 231 },
  { id: 'donphan', name: 'Donphan', emoji: '•', spriteId: 232 },
  { id: 'porygon2', name: 'Porygon2', emoji: '•', spriteId: 233 },
  { id: 'stantler', name: 'Stantler', emoji: '•', spriteId: 234 },
  { id: 'smeargle', name: 'Smeargle', emoji: '•', spriteId: 235 },
  { id: 'tyrogue', name: 'Tyrogue', emoji: '•', spriteId: 236 },
  { id: 'hitmontop', name: 'Hitmontop', emoji: '•', spriteId: 237 },
  { id: 'smoochum', name: 'Smoochum', emoji: '•', spriteId: 238 },
  { id: 'elekid', name: 'Elekid', emoji: '•', spriteId: 239 },
  { id: 'magby', name: 'Magby', emoji: '•', spriteId: 240 },
  { id: 'miltank', name: 'Miltank', emoji: '•', spriteId: 241 },
  { id: 'blissey', name: 'Blissey', emoji: '•', spriteId: 242 },
  { id: 'raikou', name: 'Raikou', emoji: '•', spriteId: 243 },
  { id: 'entei', name: 'Entei', emoji: '•', spriteId: 244 },
  { id: 'suicune', name: 'Suicune', emoji: '•', spriteId: 245 },
  { id: 'larvitar', name: 'Larvitar', emoji: '•', spriteId: 246 },
  { id: 'pupitar', name: 'Pupitar', emoji: '•', spriteId: 247 },
  { id: 'tyranitar', name: 'Tyranitar', emoji: '•', spriteId: 248 },
  { id: 'lugia', name: 'Lugia', emoji: '•', spriteId: 249 },
  { id: 'ho-oh', name: 'Ho-Oh', emoji: '•', spriteId: 250 },
  { id: 'celebi', name: 'Celebi', emoji: '•', spriteId: 251 }
]

// Evolution stage: 0 = base (3 questions), 1 = 1st evolution (4), 2 = 2nd evolution (5)
const EVOLUTION_STAGE = {
  bulbasaur: 0, ivysaur: 1, venusaur: 2, charmander: 0, charmeleon: 1, charizard: 2,
  squirtle: 0, wartortle: 1, blastoise: 2, caterpie: 0, metapod: 1, butterfree: 2,
  weedle: 0, kakuna: 1, beedrill: 2, pidgey: 0, pidgeotto: 1, pidgeot: 2,
  rattata: 0, raticate: 1, spearow: 0, fearow: 1, ekans: 0, arbok: 1,
  pikachu: 0, raichu: 1, sandshrew: 0, sandslash: 1, 'nidoran-f': 0, nidorina: 1, nidoqueen: 2,
  'nidoran-m': 0, nidorino: 1, nidoking: 2, clefairy: 0, clefable: 1, vulpix: 0, ninetales: 1,
  jigglypuff: 0, wigglytuff: 1, zubat: 0, golbat: 1, crobat: 2, oddish: 0, gloom: 1, vileplume: 2,
  paras: 0, parasect: 1, venonat: 0, venomoth: 1, diglett: 0, dugtrio: 1,
  meowth: 0, persian: 1, psyduck: 0, golduck: 1, mankey: 0, primeape: 1,
  growlithe: 0, arcanine: 1, poliwag: 0, poliwhirl: 1, poliwrath: 2, politoed: 2,
  abra: 0, kadabra: 1, alakazam: 2, machop: 0, machoke: 1, machamp: 2,
  bellsprout: 0, weepinbell: 1, victreebel: 2, tentacool: 0, tentacruel: 1,
  geodude: 0, graveler: 1, golem: 2, ponyta: 0, rapidash: 1, slowpoke: 0, slowbro: 1, slowking: 1,
  magnemite: 0, magneton: 1, farfetchd: 0, doduo: 0, dodrio: 1, seel: 0, dewgong: 1,
  grimer: 0, muk: 1, shellder: 0, cloyster: 1, gastly: 0, haunter: 1, gengar: 2,
  onix: 0, steelix: 1, drowzee: 0, hypno: 1, krabby: 0, kingler: 1, voltorb: 0, electrode: 1,
  exeggcute: 0, exeggutor: 1, cubone: 0, marowak: 1, hitmonlee: 0, hitmonchan: 0, tyrogue: 0, hitmontop: 0,
  lickitung: 0, koffing: 0, weezing: 1, rhyhorn: 0, rhydon: 1, chansey: 0, blissey: 1, tangela: 0,
  kangaskhan: 0, horsea: 0, seadra: 1, kingdra: 2, goldeen: 0, seaking: 1, staryu: 0, starmie: 1,
  'mr-mime': 0, scyther: 0, scizor: 1, jynx: 0, electabuzz: 0, magmar: 0, pinsir: 0, tauros: 0,
  magikarp: 0, gyarados: 1, lapras: 0, ditto: 0, eevee: 0, vaporeon: 1, jolteon: 1, flareon: 1, espeon: 1, umbreon: 1,
  porygon: 0, porygon2: 1, omanyte: 0, omastar: 1, kabuto: 0, kabutops: 1, aerodactyl: 0, snorlax: 0,
  articuno: 0, zapdos: 0, moltres: 0, dratini: 0, dragonair: 1, dragonite: 2, mewtwo: 0, mew: 0,
  bellossom: 2, chikorita: 0, bayleef: 1, meganium: 2, cyndaquil: 0, quilava: 1, typhlosion: 2,
  totodile: 0, croconaw: 1, feraligatr: 2, sentret: 0, furret: 1, hoothoot: 0, noctowl: 1,
  ledyba: 0, ledian: 1, spinarak: 0, ariados: 1, chinchou: 0, lanturn: 1, pichu: 0, cleffa: 0,
  igglybuff: 0, togepi: 0, togetic: 1, natu: 0, xatu: 1, mareep: 0, flaaffy: 1, ampharos: 2,
  marill: 0, azumarill: 1, sudowoodo: 0, hoppip: 0, skiploom: 1, jumpluff: 2, aipom: 0, sunkern: 0,
  sunflora: 1, yanma: 0, wooper: 0, quagsire: 1, murkrow: 0, misdreavus: 0, unown: 0, wobbuffet: 0,
  girafarig: 0, pineco: 0, forretress: 1, dunsparce: 0, gligar: 0, snubbull: 0, granbull: 1,
  qwilfish: 0, shuckle: 0, heracross: 0, sneasel: 0, teddiursa: 0, ursaring: 1, slugma: 0,
  magcargo: 1, swinub: 0, piloswine: 1, corsola: 0, remoraid: 0, octillery: 1, delibird: 0,
  mantine: 0, skarmory: 0, houndour: 0, houndoom: 1, phanpy: 0, donphan: 1, stantler: 0,
  smeargle: 0, smoochum: 0, elekid: 0, magby: 0, miltank: 0, raikou: 0, entei: 0,
  suicune: 0, larvitar: 0, pupitar: 1, tyranitar: 2, lugia: 0, 'ho-oh': 0, celebi: 0
}

// Next evolution: id -> next form id, or null if fully evolved / multi-evolution / no evolution
const NEXT_EVOLUTION = {
  bulbasaur: 'ivysaur', ivysaur: 'venusaur', venusaur: null, charmander: 'charmeleon', charmeleon: 'charizard', charizard: null,
  squirtle: 'wartortle', wartortle: 'blastoise', blastoise: null, caterpie: 'metapod', metapod: 'butterfree', butterfree: null,
  weedle: 'kakuna', kakuna: 'beedrill', beedrill: null, pidgey: 'pidgeotto', pidgeotto: 'pidgeot', pidgeot: null,
  rattata: 'raticate', raticate: null, spearow: 'fearow', fearow: null, ekans: 'arbok', arbok: null,
  pichu: 'pikachu', pikachu: 'raichu', raichu: null, sandshrew: 'sandslash', sandslash: null, 'nidoran-f': 'nidorina', nidorina: 'nidoqueen', nidoqueen: null,
  'nidoran-m': 'nidorino', nidorino: 'nidoking', nidoking: null, cleffa: 'clefairy', clefairy: 'clefable', clefable: null, vulpix: 'ninetales', ninetales: null,
  igglybuff: 'jigglypuff', jigglypuff: 'wigglytuff', wigglytuff: null, zubat: 'golbat', golbat: 'crobat', crobat: null, oddish: 'gloom', gloom: null, vileplume: null, bellossom: null,
  paras: 'parasect', parasect: null, venonat: 'venomoth', venomoth: null, diglett: 'dugtrio', dugtrio: null,
  meowth: 'persian', persian: null, psyduck: 'golduck', golduck: null, mankey: 'primeape', primeape: null,
  growlithe: 'arcanine', arcanine: null, poliwag: 'poliwhirl', poliwhirl: null, poliwrath: null, politoed: null,
  abra: 'kadabra', kadabra: 'alakazam', alakazam: null, machop: 'machoke', machoke: 'machamp', machamp: null,
  bellsprout: 'weepinbell', weepinbell: 'victreebel', victreebel: null, tentacool: 'tentacruel', tentacruel: null,
  geodude: 'graveler', graveler: 'golem', golem: null, ponyta: 'rapidash', rapidash: null, slowpoke: null, slowbro: null, slowking: null,
  magnemite: 'magneton', magneton: null, farfetchd: null, doduo: 'dodrio', dodrio: null, seel: 'dewgong', dewgong: null,
  grimer: 'muk', muk: null, shellder: 'cloyster', cloyster: null, gastly: 'haunter', haunter: 'gengar', gengar: null,
  onix: 'steelix', steelix: null, drowzee: 'hypno', hypno: null, krabby: 'kingler', kingler: null, voltorb: 'electrode', electrode: null,
  exeggcute: 'exeggutor', exeggutor: null, cubone: 'marowak', marowak: null, tyrogue: null, hitmonlee: null, hitmonchan: null, hitmontop: null,
  lickitung: null, koffing: 'weezing', weezing: null, rhyhorn: 'rhydon', rhydon: null, chansey: 'blissey', blissey: null, tangela: null,
  kangaskhan: null, horsea: 'seadra', seadra: 'kingdra', kingdra: null, goldeen: 'seaking', seaking: null, staryu: 'starmie', starmie: null,
  'mr-mime': null, scyther: 'scizor', scizor: null, smoochum: 'jynx', jynx: null, elekid: 'electabuzz', electabuzz: null, magby: 'magmar', magmar: null, pinsir: null, tauros: null,
  magikarp: 'gyarados', gyarados: null, lapras: null, ditto: null, eevee: null, vaporeon: null, jolteon: null, flareon: null, espeon: null, umbreon: null,
  porygon: 'porygon2', porygon2: null, omanyte: 'omastar', omastar: null, kabuto: 'kabutops', kabutops: null, aerodactyl: null, snorlax: null,
  articuno: null, zapdos: null, moltres: null, dratini: 'dragonair', dragonair: 'dragonite', dragonite: null, mewtwo: null, mew: null,
  chikorita: 'bayleef', bayleef: 'meganium', meganium: null, cyndaquil: 'quilava', quilava: 'typhlosion', typhlosion: null,
  totodile: 'croconaw', croconaw: 'feraligatr', feraligatr: null, sentret: 'furret', furret: null, hoothoot: 'noctowl', noctowl: null,
  ledyba: 'ledian', ledian: null, spinarak: 'ariados', ariados: null, chinchou: 'lanturn', lanturn: null,
  togepi: 'togetic', togetic: null, natu: 'xatu', xatu: null, mareep: 'flaaffy', flaaffy: 'ampharos', ampharos: null,
  marill: 'azumarill', azumarill: null, sudowoodo: null, hoppip: 'skiploom', skiploom: 'jumpluff', jumpluff: null,
  aipom: null, sunkern: 'sunflora', sunflora: null, yanma: null, wooper: 'quagsire', quagsire: null, murkrow: null, misdreavus: null,
  unown: null, wobbuffet: null, girafarig: null, pineco: 'forretress', forretress: null, dunsparce: null, gligar: null,
  snubbull: 'granbull', granbull: null, qwilfish: null, shuckle: null, heracross: null, sneasel: null, teddiursa: 'ursaring', ursaring: null,
  slugma: 'magcargo', magcargo: null, swinub: 'piloswine', piloswine: null, corsola: null, remoraid: 'octillery', octillery: null,
  delibird: null, mantine: null, skarmory: null, houndour: 'houndoom', houndoom: null, phanpy: 'donphan', donphan: null,
  stantler: null, smeargle: null, miltank: null, raikou: null, entei: null, suicune: null, larvitar: 'pupitar', pupitar: 'tyranitar', tyranitar: null,
  lugia: null, 'ho-oh': null, celebi: null
}

// Pokémon with multiple possible evolutions (e.g. Eevee) – id -> array of next form ids
const MULTI_EVOLUTIONS = {
  eevee: ['vaporeon', 'jolteon', 'flareon', 'espeon', 'umbreon'],
  gloom: ['vileplume', 'bellossom'],
  poliwhirl: ['poliwrath', 'politoed'],
  slowpoke: ['slowbro', 'slowking'],
  tyrogue: ['hitmonlee', 'hitmonchan', 'hitmontop']
}

// Base form of each evolution line (first form in chain)
const BASE_FORM = {
  bulbasaur: 'bulbasaur', ivysaur: 'bulbasaur', venusaur: 'bulbasaur', charmander: 'charmander', charmeleon: 'charmander', charizard: 'charmander',
  squirtle: 'squirtle', wartortle: 'squirtle', blastoise: 'squirtle', caterpie: 'caterpie', metapod: 'caterpie', butterfree: 'caterpie',
  weedle: 'weedle', kakuna: 'weedle', beedrill: 'weedle', pidgey: 'pidgey', pidgeotto: 'pidgey', pidgeot: 'pidgey',
  rattata: 'rattata', raticate: 'rattata', spearow: 'spearow', fearow: 'spearow', ekans: 'ekans', arbok: 'ekans',
  pichu: 'pichu', pikachu: 'pichu', raichu: 'pichu', sandshrew: 'sandshrew', sandslash: 'sandshrew', 'nidoran-f': 'nidoran-f', nidorina: 'nidoran-f', nidoqueen: 'nidoran-f',
  'nidoran-m': 'nidoran-m', nidorino: 'nidoran-m', nidoking: 'nidoran-m', cleffa: 'cleffa', clefairy: 'cleffa', clefable: 'cleffa', vulpix: 'vulpix', ninetales: 'vulpix',
  igglybuff: 'igglybuff', jigglypuff: 'igglybuff', wigglytuff: 'igglybuff', zubat: 'zubat', golbat: 'zubat', crobat: 'zubat', oddish: 'oddish', gloom: 'oddish', vileplume: 'oddish', bellossom: 'oddish',
  paras: 'paras', parasect: 'paras', venonat: 'venonat', venomoth: 'venonat', diglett: 'diglett', dugtrio: 'diglett',
  meowth: 'meowth', persian: 'meowth', psyduck: 'psyduck', golduck: 'psyduck', mankey: 'mankey', primeape: 'mankey',
  growlithe: 'growlithe', arcanine: 'growlithe', poliwag: 'poliwag', poliwhirl: 'poliwag', poliwrath: 'poliwag', politoed: 'poliwag',
  abra: 'abra', kadabra: 'abra', alakazam: 'abra', machop: 'machop', machoke: 'machop', machamp: 'machop',
  bellsprout: 'bellsprout', weepinbell: 'bellsprout', victreebel: 'bellsprout', tentacool: 'tentacool', tentacruel: 'tentacool',
  geodude: 'geodude', graveler: 'geodude', golem: 'geodude', ponyta: 'ponyta', rapidash: 'ponyta', slowpoke: 'slowpoke', slowbro: 'slowpoke', slowking: 'slowpoke',
  magnemite: 'magnemite', magneton: 'magnemite', farfetchd: 'farfetchd', doduo: 'doduo', dodrio: 'doduo', seel: 'seel', dewgong: 'seel',
  grimer: 'grimer', muk: 'grimer', shellder: 'shellder', cloyster: 'shellder', gastly: 'gastly', haunter: 'gastly', gengar: 'gastly',
  onix: 'onix', steelix: 'onix', drowzee: 'drowzee', hypno: 'drowzee', krabby: 'krabby', kingler: 'krabby', voltorb: 'voltorb', electrode: 'voltorb',
  exeggcute: 'exeggcute', exeggutor: 'exeggcute', cubone: 'cubone', marowak: 'cubone', tyrogue: 'tyrogue', hitmonlee: 'tyrogue', hitmonchan: 'tyrogue', hitmontop: 'tyrogue',
  lickitung: 'lickitung', koffing: 'koffing', weezing: 'koffing', rhyhorn: 'rhyhorn', rhydon: 'rhyhorn', chansey: 'chansey', blissey: 'chansey', tangela: 'tangela',
  kangaskhan: 'kangaskhan', horsea: 'horsea', seadra: 'horsea', kingdra: 'horsea', goldeen: 'goldeen', seaking: 'goldeen', staryu: 'staryu', starmie: 'staryu',
  'mr-mime': 'mr-mime', scyther: 'scyther', scizor: 'scyther', smoochum: 'smoochum', jynx: 'smoochum', elekid: 'elekid', electabuzz: 'elekid', magby: 'magby', magmar: 'magby', pinsir: 'pinsir', tauros: 'tauros',
  magikarp: 'magikarp', gyarados: 'magikarp', lapras: 'lapras', ditto: 'ditto', eevee: 'eevee', vaporeon: 'eevee', jolteon: 'eevee', flareon: 'eevee', espeon: 'eevee', umbreon: 'eevee',
  porygon: 'porygon', porygon2: 'porygon', omanyte: 'omanyte', omastar: 'omanyte', kabuto: 'kabuto', kabutops: 'kabuto', aerodactyl: 'aerodactyl', snorlax: 'snorlax',
  articuno: 'articuno', zapdos: 'zapdos', moltres: 'moltres', dratini: 'dratini', dragonair: 'dratini', dragonite: 'dratini', mewtwo: 'mewtwo', mew: 'mew',
  chikorita: 'chikorita', bayleef: 'chikorita', meganium: 'chikorita', cyndaquil: 'cyndaquil', quilava: 'cyndaquil', typhlosion: 'cyndaquil',
  totodile: 'totodile', croconaw: 'totodile', feraligatr: 'totodile', sentret: 'sentret', furret: 'sentret', hoothoot: 'hoothoot', noctowl: 'hoothoot',
  ledyba: 'ledyba', ledian: 'ledyba', spinarak: 'spinarak', ariados: 'spinarak', chinchou: 'chinchou', lanturn: 'chinchou',
  togepi: 'togepi', togetic: 'togepi', natu: 'natu', xatu: 'natu', mareep: 'mareep', flaaffy: 'mareep', ampharos: 'mareep',
  marill: 'marill', azumarill: 'marill', sudowoodo: 'sudowoodo', hoppip: 'hoppip', skiploom: 'hoppip', jumpluff: 'hoppip',
  aipom: 'aipom', sunkern: 'sunkern', sunflora: 'sunkern', yanma: 'yanma', wooper: 'wooper', quagsire: 'wooper', murkrow: 'murkrow', misdreavus: 'misdreavus',
  unown: 'unown', wobbuffet: 'wobbuffet', girafarig: 'girafarig', pineco: 'pineco', forretress: 'pineco', dunsparce: 'dunsparce', gligar: 'gligar',
  snubbull: 'snubbull', granbull: 'snubbull', qwilfish: 'qwilfish', shuckle: 'shuckle', heracross: 'heracross', sneasel: 'sneasel',
  teddiursa: 'teddiursa', ursaring: 'teddiursa', slugma: 'slugma', magcargo: 'slugma', swinub: 'swinub', piloswine: 'swinub',
  corsola: 'corsola', remoraid: 'remoraid', octillery: 'remoraid', delibird: 'delibird', mantine: 'mantine', skarmory: 'skarmory',
  houndour: 'houndour', houndoom: 'houndour', phanpy: 'phanpy', donphan: 'phanpy', stantler: 'stantler', smeargle: 'smeargle', miltank: 'miltank',
  raikou: 'raikou', entei: 'entei', suicune: 'suicune', larvitar: 'larvitar', pupitar: 'larvitar', tyranitar: 'larvitar',
  lugia: 'lugia', 'ho-oh': 'ho-oh', celebi: 'celebi'
}

// Starters: always selectable. Extra caught Pokémon are loaded from data/caught.json
const STARTER_IDS = ['bulbasaur', 'charmander', 'squirtle', 'pikachu', 'eevee']
